# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KW9KT5NUdL6I2tLd3D0oOAJDeKC8gylV
"""

#import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image, ImageFilter
from google.colab.patches import cv2_imshow


#ısı
img = cv2.imread('/rrrrrrrrrrr.jpg')


heatmap = cv2.applyColorMap(img, cv2.COLORMAP_JET)


plt.imshow(heatmap)
plt.show()

#Siyah beyaz filtre
img = Image.open('/rrrrrrrrrrr.jpg')
img = img.convert("L")  # Convert to grayscale
img.show()

#Renk değiştirme filtresi
img = Image.open('/rrrrrrrrrrr.jpg')
r, g, b = img.split()
img = Image.merge("RGB", (b, g, r))  # Swap R and B channels
img.show()

#Blur filtresi
img = Image.open('/rrrrrrrrrrr.jpg')
img = img.filter(ImageFilter.BLUR) 
img.show()

#Keskinleştirme filtresi

img = Image.open('/rrrrrrrrrrr.jpg')
img = img.filter(ImageFilter.SHARPEN)  # Apply sharpen filter
img.show()

#yüzey filtresi
img = Image.open('/rrrrrrrrrrr.jpg')
img = img.filter(ImageFilter.EDGE_ENHANCE)  # Apply edge enhancement filter
img.show()

#Median Filter
img = cv2.imread('/rrrrrrrrrrr.jpg')

# Median Filtre uygula
median = cv2.medianBlur(img, 5)

# Görüntüyü göster
cv2_imshow(median)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Gaussian Filter


# Resmi yükle
img = cv2.imread('/rrrrrrrrrrr.jpg')

# Gaussian Filtre uygula
gaussian = cv2.GaussianBlur(img, (5,5), 0)

# Görüntüyü göster
cv2_imshow(gaussian)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Bilateral Filter


# Resmi yükle
img = cv2.imread('/rrrrrrrrrrr.jpg')

# Bilateral Filtre uygula
bilateral = cv2.bilateralFilter(img, 9, 75, 75)

# Görüntüyü göster
cv2_imshow(bilateral)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Laplacian Filter
# Resmi yükle
img = cv2.imread('/rrrrrrrrrrr.jpg')

# Grayscale çevir
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Laplacian Filtre uygula
laplacian = cv2.Laplacian(gray, cv2.CV_64F)

# Görüntüyü göster
cv2_imshow(laplacian)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Sobel Filter


# Resmi yükle
img = cv2.imread('/rrrrrrrrrrr.jpg')

# Grayscale çevir
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Sobel Filtre uygula
sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=5)
sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=5)
sobel = cv2.addWeighted(sobel_x, 0.5, sobel_y, 0.5, 0)

# Görüntüyü göster
cv2_imshow(sobel)
cv2.waitKey(0)
cv2.destroyAllWindows()

img = cv2.imread('/rrrrrrrrrrr.jpg', cv2.IMREAD_GRAYSCALE)

# Sarı-lacivert renklerin RGB değerlerini belirle
yellow = (255, 206, 0)
navy = (0, 30, 63)

# Siyah-beyaz resmi sarı-lacivert renk paletine dönüştür
colored_img = np.zeros((img.shape[0], img.shape[1], 3), dtype=np.uint8)
colored_img[:,:,0] = img
colored_img[:,:,1] = img
colored_img[:,:,2] = img
colored_img[img > 127] = yellow
colored_img[img <= 127] = navy

# Görüntüyü göster
cv2_imshow(colored_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

